FROM debian:buster-20211220

LABEL maintainer = "Rolf Seewaldt"

ARG USER_ARG

RUN mkdir /downloads
WORKDIR /downloads

RUN apt update && apt install -y wget
RUN wget https://go.dev/dl/go1.17.5.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf go1.17.5.linux-amd64.tar.gz
ENV PATH=$PATH:/usr/local/go/bin

RUN useradd -ms /bin/bash $USER_ARG
USER $USER_ARG 

COPY . /go/src/gitlab.com/andersph/docker-master-class/api
WORKDIR /go/src/gitlab.com/andersph/docker-master-class/api

ENTRYPOINT [ "bash", "-c", "go run main.go" ]